# omakux — GTK 3/4 (GENERADO: omakux theme set <nombre>)
# tus apps GTK (Nautilus, Settings, apps de terceros) leen esto
[Settings]
gtk-theme-name={{gtk_theme}}
gtk-icon-theme-name={{icon_theme}}
gtk-cursor-theme-name={{cursor_theme}}
gtk-cursor-theme-size=24
gtk-font-name={{ui_font}}
gtk-application-prefer-dark-theme={{gtk_dark}}
gtk-enable-animations=true
gtk-primary-button-warps-slider=true
