# omakux — dunst (GENERADO: omakux theme set <nombre>)
[global]
    font = JetBrains Mono 11
    format = "<b>%s</b>\n%b"
    width = 420
    offset = "16x48"
    origin = "top-right"
    shrink = true
    transparency = 8
    frame_width = 2
    frame_color = "{{color_accent}}"
    corner_radius = 12
    padding = 12
    horizontal_padding = 14
    markup = full
    indicate_hidden = yes
    icon_position = left
    max_icon_size = 48
    sort = yes
    idle_threshold = 120
    follow = mouse
    layer = overlay
    corner_radius = 12

[urgency_low]
    background = "{{color_surface}}"
    foreground = "{{color_muted}}"
    timeout = 4

[urgency_normal]
    background = "{{color_surface}}"
    foreground = "{{color_fg}}"
    timeout = 6

[urgency_critical]
    background = "{{color_red}}"
    foreground = "{{color_bg}}"
    frame_color = "{{color_red}}"
    timeout = 0
