# omakux — hyprlock (GENERADO: omakux theme set <nombre>)
general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 1
}

background {
    monitor =
    path = ~/.local/state/omakux/wallpapers/active.png
    blur_passes = 3
    blur_size = 6
    noise = 0.011
    brightness = 0.7
    contrast = 1.1
}

label {
    monitor =
    text = $TIME
    font_size = 96
    font_family = JetBrains Mono
    color = rgb({{color_fg_rgb}})
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A %d de %B')"
    font_size = 18
    font_family = JetBrains Mono
    color = rgba({{color_muted_a}})
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.26
    dots_spacing = 0.3
    outer_color = rgb({{color_accent_rgb}})
    inner_color = rgb({{color_bg_rgb}})
    font_color = rgb({{color_fg_rgb}})
    check_color = rgb({{color_green_rgb}})
    fail_color = rgb({{color_red_rgb}})
    placeholder_text = <i>contraseña…</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -40
    halign = center
    valign = center
}
