# omakux — tmux colors (GENERADO: omakux theme set <nombre>)
set -g status-style "bg={{color_surface}},fg={{color_fg}}"
set -g status-left "#[fg={{color_bg}},bg={{color_accent}},bold] #S #[fg={{color_fg}},bg={{color_surface}}]· "
set -g status-right "#[fg={{color_muted}}]#h · %H:%M "
setw -g window-status-style "fg={{color_muted}},bg=default"
setw -g window-status-current-style "fg={{color_bg}},bg={{color_accent}},bold"
setw -g window-status-activity-style "fg={{color_yellow}},bg=default"
set -g pane-active-border-style "fg={{color_accent}}"
set -g pane-border-style "fg={{color_border}}"
set -g message-style "fg={{color_fg}},bg={{color_surface}}"
set -g message-command-style "fg={{color_fg}},bg={{color_surface}}"
set -g mode-style "fg={{color_bg}},bg={{color_accent}}"
