# omakux — tmux config
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 10
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# splits razonables
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux recargado"

# navegación tipo vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# copia
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# colores del tema activo (generado por omakux theme set)
if-shell '[ -f ~/.config/tmux/colors.conf ]' 'source-file ~/.config/tmux/colors.conf'

set -g status on
set -g status-position top
set -g status-interval 5
set -g status-style "bg=default,fg=default"
set -g status-left-length 40
set -g status-right-length 60
set -g status-left "#[bold] #S #[default]· "
set -g status-right "#h · %H:%M "
setw -g window-status-current-format "#[bold]#I:#W*"
setw -g window-status-format "#I:#W"
